insert into "dnd-mini".miniature (model_name,model_type,origin,set_number,set_number_variant,creature_name,creature_type_code,creature_subtype_code,creature_size,base_diameter_inches,num_owned) values
('Troll','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',35,null,'Troll',9,70,'large',2,2),
('Fomorian','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',34,null,'Fomorian',9,null,'huge',3,2),
('Giant Snail','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',33,null,'Giant Snail',2,null,'large',2,2),
('Glister','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',14,null,'Selenelion Twin',10,8,'medium',1,2),
('Bullywug Knight','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',4,null,'Bullywug',10,3,'medium',1,2),
('Peryton','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',23,null,'Peryton',11,80,'medium',1,2),
('Darkling Elder','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',25,null,'Darkling Elder',7,null,'medium',1,2),
('Myconid Adult','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',10,null,'Myconid Adult',13,81,'medium',1,2),
('Giant Dragonfly','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',31,null,'Giant Dragonfly',2,null,'large',2,2),
('Grell','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',26,null,'Grell',1,null,'medium',1,2),
('Cradlefall','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',30,null,'Green Dragon Wyrmling',5,59,'medium',1,2),
('Clapperclaw','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',22,null,'Scarecrow',4,null,'medium',1,2),
('Bullywug Royal','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',28,null,'Bullywug',10,3,'medium',1,2),
('Giant Toad','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',32,null,'Giant Toad',2,null,'large',2,2),
('Gleam','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',15,null,'Selenelion Twin',10,8,'medium',1,3),
('Darkling','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',5,null,'Darkling',7,null,'small',0.75,2),
('Will','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',20,null,'Human',10,14,'medium',1,2),
('Star','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',21,null,'Displacer Beast',11,null,'small',1,1),
('Sir Talavar','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',17,null,'Faerie Dragon',5,62,'tiny',0.75,2),
('Quickling','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',11,null,'Quickling',7,null,'tiny',0.75,2),
('Redcap','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',9,null,'Redcap',7,null,'small',0.75,2),
('Campestri','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',12,null,'Campestri',13,null,'tiny',0.75,4),
('Pincushion','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',37,null,'Living Doll',4,58,'tiny',0.75,2),
('Tumblestrum & Groak','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',39,null,'Gnome',10,24,'small',1,2),
('Feywild Goblin','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',2,null,'Goblin',10,20,'small',0.75,2),
('Squirt','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',19,null,'Construct',4,58,'tiny',0.75,2),
('Brigganock Miner','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',1,null,'Brigganock',7,null,'tiny',0.75,2),
('Amidor','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',27,null,'Plant',13,null,'small',0.75,2),
('Korred','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',8,null,'Korred',7,null,'small',0.75,2),
('Bobby','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',13,null,'Human',10,14,'medium',1,1),
('Gullop the XIX','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',38,null,'Bullywug',10,3,'medium',1,1),
('Harengon Brigand','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',3,null,'Harengon',10,86,'medium',1,2),
('Iggwilv''s Cauldron (Iron)','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',49,null,'Magic Item',15,null,'medium',1,2),
('Harengon Brigand with Poleaxe','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight - Pre-order Bonus',null,null,'Harengon',10,86,'medium',1,1),
('Harengon Brigand with Longbow','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight - Pre-order Bonus',null,null,'Harengon',10,86,'medium',1,1),
('Jabberwock','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',48,null,'Jabberwock',5,62,'huge',3,1),
('Unicorn Horn','Wizkids Pre-painted','Icons of the Realms - The Wild Beyond the Witchlight',null,null,'Item',15,null,'small',0.5,2);